apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: project
  labels: 
    app: backend
    tier: backend
    project: project
spec:
  replicas: 1 ## {{ .Values.deployment.replicas }}
  selector: 
    matchLabels:
      app: backend
      tier: backend
      project: project
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: project
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.deployment.imageURL }}:{{ .Values.deployment.version }}"
        envFrom:
        - configMapRef:
            name: backend